#!/usr/bin/env python

import click
import app.local_file_persistence as persistence
from app.task import Task
from os import path


tasks = []
gtu_dir = '/Users/jarias/gtu'
# @click.command()
# @click.argument('command', default='meh')
# def gtu(command):
#     print('command: '+command)
@click.group()
def gtu():
    pass

@gtu.command()
@click.argument('task_title', required=True)
def add(task_title):
    click.echo('adding a new task')
    task = Task(task_title)
    persistence.save(task)

@gtu.command()
def ls():
    click.echo('ls tasks... pending implementation')
    for task in tasks:
        print(task)

if __name__ == '__main__':
    gtu()
